server:
  port: '8083'

---
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    driverClassName: com.mysql.jdbc.Driver
    password: 21276@root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Spring Boot

management:
  endpoints:
    web:
      exposure:
        include: '*'


---
spring:
  profiles: qa
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    driverClassName: com.mysql.jdbc.Driver
    password: 21276@root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Spring Boot


